FROM golang:1.14-alpine as builder

ENV GO111MODULE=on

WORKDIR /

COPY . .

RUN apk --no-cache add git alpine-sdk build-base gcc

RUN go build -tags musl -o ./bin/consumer consumer/*.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates bash

WORKDIR /

COPY --from=builder /bin/consumer .
COPY --from=builder /wait-for-it.sh .

RUN chmod +x ./consumer

EXPOSE 8080

CMD ["./consumer"]